### ISSUE TITLE
Switch to main branch and use official docker image

### ISSUE THREAD

**Issue by Dr-Electron** [jelastic-jps/iota-node#4]
Hi, great work with this easy hornet setup.

But I think you should switch to the main branch, or at least provide the possibility to choose. 
The develop branch isn’t always stable. For example, with the current update to 1.0.3 people still get version 1.0.2 with the dev branch and the miss the newest config.
Also, did you think about simply using the latest docker image, so you don’t need to build yourself?
<https://hub.docker.com/r/gohornet/hornet>

**Comment by ihorman** [comment]
Hi,  thank you for reporting the issue.  We've switched to the main branch as you suggested. The reason why we used devel branch before was that some changes were not merged to into main branch when hornet version was released (related to docker), but now all seems to work. The reason why we build from sources instead of using already pre-built docker image was related to issues with docker pull limitations from dockerhub when they have announced their new policy related to amount of free pulls per 6 hours.
